# Generated by Django 4.0.5 on 2022-06-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='Flights',
        ),
    ]
