# Generated by Django 4.0.5 on 2022-06-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_rename_flight_flights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
    ]
